import "./globals.css";
import { Inter, Poppins, Sora } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const sora = Sora({ subsets: ["latin"] });
// const poppins = Poppins({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sora.className}>
        {/* add noise texture (img) as bg and set it to -1000 z index */}
        <div className="absolute inset-0 z-[-1000]">
          <img src="/noise.png" alt="" className="object-cover w-full h-full" />
        </div>
        {children}
      </body>
    </html>
  );
}
